name: Publish Stable

on:
  push:
    tags:
      - "*"

jobs:
  publish-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Temporal fix for https://github.com/jgitver/jgitver/issues/149
      - name: Checkout
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          # The name of the environment variable, not its value
          gpg-passphrase: OSSRH_GPG_SECRET_KEY_PASSWORD

      - name: List GPG Keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Print version
        run: ./gradlew version

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

      - name: Publish
        run: ./gradlew -Prelease -Psigning.gnupg.keyName=${{ secrets.OSSRH_GPG_SECRET_KEY_ID }} -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release in OSSRH
        run: ./gradlew closeAndReleaseRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Java client library for the [Notifir](https://notifir.github.io/docs/).

            Grab the new version from Maven central https://repo1.maven.org/maven2/io/github/notifir/notifir/${{ github.ref_name }}/:

            ```
            <dependency>
              <groupId>io.github.notifir</groupId>
              <artifactId>notifir</artifactId>
              <version>${{ github.ref_name }}</version>
            </dependency>
            ```

            Or using Gradle:

            ```
            implementation 'io.github.notifir:notifir:${{ github.ref_name }}'
            ```

            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
