name: Publish Stable

on:
  push:
    tags:
      - "*"

jobs:
  publish-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Temporal fix for https://github.com/jgitver/jgitver/issues/149
      - name: Checkout
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          # The name of the environment variable, not its value
          gpg-passphrase: OSSRH_GPG_SECRET_KEY_PASSWORD

      - name: List GPG Keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Print version
        run: ./gradlew version

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test

      - name: Publish
        run: ./gradlew -Prelease -Psigning.gnupg.keyName=${{ secrets.OSSRH_GPG_SECRET_KEY_ID }} -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Repository in OSSRH
        run: ./gradlew closeAndReleaseRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
